### ISSUE TITLE
Session timeout message still displaying in Spanish for English locale

### ISSUE THREAD

**Issue by JohnGillanders** [coopdevs/timeoverflow#694] opened 2023-05-21 22:16 UTC
For a user with English language selected, the message that appears about the session timing out still displays as Spanish (on last test, a few weeks ago):
"Tu sesión ha caducado. Por favor, regístrate nuevamente para continuar."
Please translate to English.

**Comment by markets** [comment] 2023-11-23 13:52
Fixed by #712, it will be live in next release!

**Closed by markets** 2023-11-23 13:52 UTC

**Comment by JohnGillanders** [comment] 2023-11-23 18:04
Great, thanks!Regards,John GillandersManaging DirectorTechnaturallywww.Technaturally.infoYour Life, Enriched by Technology027 486 1533On 24/11/2023, at 2:52 AM, Marc Anguera ***@***.***> wrote:﻿
Fixed by #712, it will be live in next release!

**Comment by nflorentin** [comment] 2024-01-15 06:45
I think that we could reopen this issue. 

I continue to have the problem in production. 

The problem is that I could not reproduce it on my local. I change Devise.timeout_in to few seconds. I sign in, I wait a few seconds, refresh my page, and I'm seeing the message in my selected language.

On production, I'am always having the message in spanish, and sometimes even in English, even though I've always the french language selected and I'm seeing the interface in French. That means that the problem is only present in Devise module.

**Comment by nflorentin** [comment] 2024-01-15 13:40
I understood the problem. 

Devise uses Warden under the hood, and Warden uses a middleware to check if session is valid, our controller defining the "set_locale" before_action is never reached, because Warden middleware cuts the request flow before it happens.

It seems to be a small fix but it is not so small, one solution would be to write a middleware to set the locale and insert this middleware before warden middleware in order to have I18n.locale set before warden middlware executes.
